### ISSUE TITLE
Use comments to parse mediawiki file

### ISSUE THREAD

**Issue by tobiasschweizer** [earwig/mwparserfromhell#105]
Hi

I have media wiki files with the following structure:

```
<!-- Begin Titel -->

some content

<!-- End Titel -->

<!-- Begin Metadaten -->

some content

<!-- End Metadaten -->

and so on ...
```

These comments express the structure of the file. So I think the method `filter_comments` is convenient to get all the "comments" as a list:

```

['<!-- Begin Titel -->', '<!-- End Titel -->', '<!-- Begin Bilder -->', '<!-- End Bilder -->', '<!-- Begin Metadaten -->', '<!-- End Metadaten -->', '<!-- Begin Transkription -->', '<!-- End Transkription -->', '<!-- Begin Referenzen -->', '<!-- End Referenzen -->', '<!-- Begin Kategorien -->', '<!-- End Kategorien -->']


```

I can get another list of all the elements of the file by accessing `nodes`.

In this list, I can now search for all the elements contained in "comments" to get the indexes of their actual content elements in `nodes`.

So the script looks like this:

```python

#!/usr/bin/env python3

import mwparserfromhell

file = open("mediawikifile", "r")
wikicode = file.read()

parsed = mwparserfromhell.parse(wikicode)

# all the comments in the file
comments = parsed.filter_comments()

# all the elements of the file (segmented according to unknown rules, at least unknown to me)
nodes = parsed.nodes

# get the contents of the first comment
begin_1 = nodes.index(comments[0])
begin_2 = nodes.index(comments[1])
contents = nodes[begin_1+1:begin_2] # get all the elements between the start and the end of the first comment

 


```

Is this there a better way to do that?

**Comment by ricordisamoa** [comment]
I use a similar technique in [itws.py](//github.com/ricordisamoa/wiki/blob/master/itws.py) for \<section\> tags.

**Comment by earwig** [comment]
That sounds like a fine way of doing it.

The only thing I can think of is using [`wikicode.get_sections()`](https://github.com/earwig/mwparserfromhell/blob/8fb5b3a6be052332f21e2343781bb32ffbfba8dd/mwparserfromhell/wikicode.py#L468) somehow? You'd have to tweak it a lot to support your specific use case, which probably isn't worth it. `get_sections` has a lot of options, but I don't see adding support for this, since there are too many possible ways to segment wikicode similar to how you're doing it.

Alternatively, you can use regex. As long as you don't have comments in the individual sections, this shouldn't cause any problems.

Closing since I don't think there's anything to do here, but feel free to ask further questions.

**Comment by tobiasschweizer** [comment]
Thank you very much for your answer!

Actually I am using regex to parse the segments enclosed by comments. So I can still use your `filter_comments` to get these sections which is quite useful.
