### ISSUE TITLE
How to get node type, content and exact tag name?

### ISSUE THREAD

**Issue by tobiasschweizer** [earwig/mwparserfromhell#106]
I want to parse some wikicode and loop over the nodes to get the type, tagname and content of each element:

```python
parsed_code = mwparserfromhell.parse(wikicode)

for node in parsed_code.nodes:
    print(type(node))

```

This prints me a list that looks like this:

```
<class 'mwparserfromhell.nodes.wikilink.Wikilink'>
<class 'mwparserfromhell.nodes.text.Text'>
<class 'mwparserfromhell.nodes.tag.Tag'>
<class 'mwparserfromhell.nodes.text.Text'>
<class 'mwparserfromhell.nodes.tag.Tag'>
<class 'mwparserfromhell.nodes.text.Text'>
<class 'mwparserfromhell.nodes.wikilink.Wikilink'>
```

Is there a direct way to access `node` in order to get the tagname, the contents etc.?

If I understand correctly, `mwparserfromhell.parse(wikicode)` returns `wikicode`, that offers `nodes`.
And each of these alements would be a member of <http://mwparserfromhell.readthedocs.org/en/latest/api/mwparserfromhell.nodes.html>.
 
Thx.

**Comment by earwig** [comment]
Yes. I'm a little confused by your question, since you already have direct access to the nodes by iterating over them as you did.

Generally you are interested in a specific type of node, not everything in the page. For this you can use `for node in parsed_code.filter_tags():` (or `filter_templates()`, or `filter_wikilinks()`, or any method described [here](http://mwparserfromhell.readthedocs.org/en/latest/api/mwparserfromhell.html#mwparserfromhell.wikicode.Wikicode.filter)).

The nodes themselves have attributes as described in the documentation you linked. So if you loop over tags, for example, you can do:

```python
for tag in parsed_code.filter_tags():
    print(tag.tag)  # Prints the name of the tag
    print(tag.contents)  # Prints the content inside of the tag
```

You can also just do `print(tag)` to print the whole thing out as a string.

**Comment by tobiasschweizer** [comment]
Thanks for your answer.

My problem is that I want to iterate sequentially over **all** the nodes irrespective of their type. I cannot make a preselection of all the tags etc. by using filter statements because I have to process all the nodes in the given sequence. 

So I will have to determine the type of the current node first and to process it adequately.

```python
parsed_code = mwparserfromhell.parse(wikicode)

for node in parsed_code.nodes:
    nodetype = type(node) # is there a better way to do that?

    # pseudocode
    if nodetype == wikilink: 
        get linkinfo
    elif nodetype == tag:
         get its type and contents
    elif nodetype == text:
        get contents

```

**Comment by ricordisamoa** [comment]
```python
for node in parsed_code.nodes:
    if isinstance(nodetype, mwparserfromhell.nodes.Wikilink):
        # get linkinfo
    elif isinstance(nodetype, mwparserfromhell.nodes.Tag):
        # get its type and contents
    elif isinstance(nodetype, mwparserfromhell.nodes.Text):
        # get contents
```

**Comment by tobiasschweizer** [comment]
Man, you saved my day!

Thank you very much!
