### ISSUE TITLE
Python 2: mwparserfromhell.parse() utf-8 file

### ISSUE THREAD

**Issue by tobiasschweizer** [earwig/mwparserfromhell#107]
Hi,

Unfortunately I had to switch to Python 2.7 (due to other module dependencies). In Python 3, I could use mwparserfromhell's parse function without problems. Now, I run into a parsing error using mwparserfromhell version 0.4:

```python
import codecs, mwparserfromhell

file = codecs.open(file_path, encoding='utf-8')
wikicode = file.read()

parsed = mwparserfromhell.parse(wikicode)

```

When I print  `parsed`, it says:

```
parsing of file failed
'ascii' codec can't encode character ...: ordinal not in range(128)
```

The var `wikicode` is of type `unicode`. Is there a way to make the parser work with those characters from a utf-8 encoded file?

Thx.

**Comment by earwig** [comment]
> Is there a way to make the parser work with those characters from a utf-8 encoded file?

It already does. The problem is that you can't _print_ these directly, which is a Python 2 quirk.

Python internal `print` code has [a special case](https://github.com/python/cpython/blob/2.7/Objects/fileobject.c#L2567-L2574) for `unicode` objects that encodes them to `sys.stdout.encoding` (`'UTF-8'` on my system). In general, though, it just [calls the object's `__str__` method](https://github.com/python/cpython/blob/2.7/Objects/object.c#L303), which has no knowledge of what encoding to use.

In mwparserfromhell's case, `parsed` is a `Wikicode` object that stores its data as unicode, but is not unicode _itself_ (because then it would have to be immutable, but you're allowed to change `Wikicode` objects). Its [`__str__` method](https://github.com/earwig/mwparserfromhell/blob/develop/mwparserfromhell/string_mixin.py#L60) is the same as calling `__str__` on the underlying unicode object. `print parsed` effectively becomes `print unicode(parsed).encode('ascii')`, which won't work when it contains non-ASCII characters.

The best thing if you really want to print it is to take advantage of the special-casing for unicode mentioned above and do the type conversion explicitly: `print unicode(parsed)`. Any other operations on the wikicode should be fine by default.

**Comment by tobiasschweizer** [comment]
Thank you very much for this detailed explanation. I find this forum very helpful.

I wanted to avoid coding in Python 2, but I am afraid there is no way around it as I have to use some modules that are only available in Python 2.
