### ISSUE TITLE
Keys and Values for inline wipiedia data templates? e.g. {{Birth date|1993|2|4|df=yes}}

### ISSUE THREAD

**Issue by rexdouglass** [earwig/mwparserfromhell#189]
I've parsed all of the infoboxes using mwparserfromhell from the english xml dump. Many of the values contain inline wikidata templates, e.g. {{flagcountry|ITA}} , {{Birth date|1993|2|4|df=yes}}.

I haven't found a dataset of the templates yet, just wikipedia descriptions and these kinds of descriptions
https://en.wikipedia.org/w/index.php?title=Template:Flagcountry&action=edit

Does this tool handle those, and if so can you give a brief example of how I could automate the processes? I'm able to retrieve values, but not key names which are defined in the templates.

**Comment by earwig** [comment]
Unfortunately, we don't have any specific handling for this. There really isn't a standard way to do it; the closest thing might be TemplateData, as seen [here](https://en.wikipedia.org/wiki/Template:Flagcountry/doc#TemplateData), but that's intended for the Visual Editor and you would still need to find the corresponding TemplateData for a particular template yourself and work out how to parse its format.

Can you say a bit more about your use case? Maybe there is another way to solve your problem.

**Comment by rexdouglass** [comment]
Sure, thanks for the feedback.

I'm parsing values in infoboxes and mapping them to wikidata or other downstream ontologies.

About 20% I'd say of the values are locked in these specific TemplateData formats, which as far as I can tell are meant to be read only by Lua scripts in a specific mediawiki extension.

I can find human readable documentation for many but not all of these templates. I find it surreal there's no machine readable export so that non-wikimedia parsers can parse the data.

I've scraped as many of those TemplateData tables as I can from the html with the goal of parsing the values myself. But there are lots of hidden gotchas, e.g. abbreviations for templates, templates that redirect to other templates, templates that have built in lookup tables like for country abbreviations.

**Comment by earwig** [comment]
That's an interesting problem, and it sounds like an accurate assessment of the situation.

I wrote a bit more of an explanation here, but I saw danmichaelo/mwtemplates#7 and realized there is a lot of overlap between that conversation and what I was going to post. Long story short, Wikipedia definitely suffers from a lack of structured data where you would expect it to be. Wikidata is the main attempt to deal with that, but there's so much institutional inertia in how we do things, and there's a struggle between those who want more standardization (seeing Wikipedia as a structured data repository) and those who don't (seeing Wikipedia as a collection of human-readable articles each with their own conventions). You could say the former group encompasses programmers/data scientists and the latter authors/writers (but that's generalizing), and we're left with something in the middle.

Ultimately, Wikipedia wasn't started with the goal of being mined by machines, so any sort of automated semantic analysis is going to be a headache, because you're using these templates for something they weren't designed for. I'm afraid there's not much else I can offer, but it sounds like you're doing the best with the tools available. Good luck.

I'm closing this ticket, but feel free to continue the conversation if you like.
