### ISSUE TITLE
Error when filtering after inserting initialized node

### ISSUE THREAD

**Issue by Larivact** [earwig/mwparserfromhell#214]
```python
import mwparserfromhell
code = mwparserfromhell.parse('foo')
tag = mwparserfromhell.nodes.Tag('bar')
code.append(tag)
code.filter()
```
results in
```
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    code.filter()
  File "/tmp/mwparserfromhell/mwparserfromhell/wikicode.py", line 550, in filter
    return list(self.ifilter(*args, **kwargs))
  File "/tmp/mwparserfromhell/mwparserfromhell/wikicode.py", line 543, in <genexpr>
    return (node for i, node in gen)
  File "/tmp/mwparserfromhell/mwparserfromhell/wikicode.py", line 108, in _indexed_ifilter
    for i, node in inodes:
  File "/tmp/mwparserfromhell/mwparserfromhell/wikicode.py", line 103, in getter
    for ch in self._get_children(node, restrict=restrict):
  File "/tmp/mwparserfromhell/mwparserfromhell/wikicode.py", line 64, in _get_children
    for child in code.nodes:
AttributeError: 'str' object has no attribute 'nodes'
```

**Comment by earwig** [comment]
This is tricky. Constructing nodes directly like that isn't something I've considered and doesn't work because Tag expects its name to be passed as a Wikicode, not a raw str. The standard way to do this would be `tag = "<bar></bar>"; code.append(tag)`.

I'm not sure whether the solution to this is supporting manual node construction in general (i.e., nodes need to run parse() over their args...), making get_children in particular more durable w.r.t. invalid node trees, or treating this as an error. I think the first solution is most correct; not exactly _difficult_ either, but it would be a bunch of things to change.

**Comment by Larivact** [comment]
Thanks for your quick reply and explanation! The use case I had was inserting a template if it doesn't exist and having immediate access to it.

```python
templates = code.filter_templates('foo')
if len(templates) > 0:
    foo = templates[0]
else:
    foo = Template('foo')
    code.insert(0, foo)
# do stuff with foo
```

When constructing nodes manually, I would expect raw strings to be treated as Text and not parsed automatically, which would amount to something like this in `Tag.__init__`:

```python
if type(tag) == str:
    tag = Wikicode([Text(tag)])
if type(contents) == str:
    tag = Wikicode([Text(contents)])
```

**Comment by earwig** [comment]
That's a reasonable use case. I think we can support this.

**Comment by earwig** [comment]
> When constructing nodes manually, I would expect raw strings to be treated as Text and not parsed automatically, which would amount to something like this in `Tag.__init__`

I decided not implement it this way because then it's easy to manually construct nodes such that `mwp.parse(str(code)).get_tree() != code.get_tree()`, which is something I try avoid.

The rest seems to work as expected.
