### ISSUE TITLE
How to get section title from results of get_sections()?

### ISSUE THREAD

**Issue by Mark-L6n** [earwig/mwparserfromhell#257]
What is the best way to get a section title from the results of `get_sections()`? 
I can do the following, but it seems there should be a better way:

``` python
wikicode = mwparserfromhell.parse(text)
sections = wikicode.get_sections()
for s in sections:
    headings = list(s.ifilter_headings())
    if headings:
        print(f'headings[0] = {headings[0]}')
```

**Comment by Riamse** [comment]
A few comments:

1. `list(s.ifilter_headings())` can be replaced with `s.filter_headings()`.
2. You can make this more concise by using a list comprehension: `[sec.filter_headings()[0] for sec in wikicode.get_sections() if sec.filter_headings()]`

**Comment by lahwaacz** [comment]
If you want to take the first heading of every section on a page, why don't you just take a list of all headings?
```python
wikicode = mwparserfromhell.parse(text)
headings = wikicode.filter_headings()
for h in headings:
    ...
```

**Comment by Mark-L6n** [comment]
> If you want to take the first heading of every section on a page, why don't you just take a list of all headings?

Because I need to call functions on the section, such as `filter_templates()`.  AFAIK, you can't do that from a heading.  
If from the results of `filter_templates()` you could find out what sections a template is in, that would work, but again AFAIK I don't think that's possible.

**Comment by earwig** [comment]
`s.filter_headings()[0]` will work fine, and seems pretty clear to me IMO.

If you want to be more concise, you can actually just do `s.get(0)` to get the first node, because the heading will *always* first assuming you passed `include_headings=True` to `get_sections()` (the default). The singular exception is the lead section, with no heading; for that, you should either ignore it with `include_lead=False` or do something different with the first section.

**Comment by Mark-L6n** [comment]
Great, thanks for the advice!
