### ISSUE TITLE
Build wheels for Python 3.10

### ISSUE THREAD

**Issue by legoktm** [earwig/mwparserfromhell#278]

**Comment by earwig** [comment]
Looks like no code changes are required, since the test suite passes with no issues.

I've updated the GH Actions to build Linux and macOS wheels for 3.10, but full integration is blocked on:
- appveyor/ci#3741 for Windows
- https://travis-ci.community/t/add-python-3-10/12220 for Travis CI

This might be a good opportunity to consider consolidating these services. I think we can use Actions for Windows and running tests? Maybe cibuildwheel is the way to go? I'm not sure.

I also dropped support for EOL 3.5.

**Comment by hugovk** [comment]
> I've updated the GH Actions to build Linux and macOS wheels for 3.10, but full integration is blocked on:
> 
> * [Python 3.10 support appveyor/ci#3741](https://github.com/appveyor/ci/issues/3741) for Windows
> * [travis-ci.community/t/add-python-3-10/12220](https://travis-ci.community/t/add-python-3-10/12220) for Travis CI

Now available on AppVeyor: https://github.com/appveyor/ci/issues/3741#issuecomment-958837889

No response at all from Travis CI.
