### ISSUE TITLE
Can't install under Colab

### ISSUE THREAD

**Issue by LeMoussel** [earwig/mwparserfromhell#321]
Under Colab, I install, in cell, the latest development version as described:
```bash
%%bash
git clone https://github.com/earwig/mwparserfromhell.git
cd mwparserfromhell
python setup.py install
```
But I got this error
```bash
running install
running bdist_egg
running egg_info
creating src/mwparserfromhell.egg-info
writing src/mwparserfromhell.egg-info/PKG-INFO
......
creating /usr/local/lib/python3.10/dist-packages/mwparserfromhell-0.7.dev0-py3.10-linux-x86_64.egg
Extracting mwparserfromhell-0.7.dev0-py3.10-linux-x86_64.egg to /usr/local/lib/python3.10/dist-packages
Adding mwparserfromhell 0.7.dev0 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/mwparserfromhell-0.7.dev0-py3.10-linux-x86_64.egg
Processing dependencies for mwparserfromhell==0.7.dev0
Finished processing dependencies for mwparserfromhell==0.7.dev0

Cloning into 'mwparserfromhell'...
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
zip_safe flag not set; analyzing archive contents...
mwparserfromhell.parser.__pycache__._tokenizer.cpython-310: module references __file__
```

**Comment by earwig** [comment]
Do you have a reason to install the development version instead of the latest release? I am unfamiliar with Colab and what exactly could be going wrong here, though we do need to update our build process, but I suspect you would be fine with the latest release). `pip install mwparserfromhell`On Mar 26, 2024, at 1:07 PM, LeMoussel ***@***.***> wrote:﻿
Under Colab, I install, in cell, the latest development version as described:
%%bash
git clone https://github.com/earwig/mwparserfromhell.git
cd mwparserfromhell
python setup.py install
But I got this error
running install
running bdist_egg
running egg_info
creating src/mwparserfromhell.egg-info
writing src/mwparserfromhell.egg-info/PKG-INFO
......
creating /usr/local/lib/python3.10/dist-packages/mwparserfromhell-0.7.dev0-py3.10-linux-x86_64.egg
Extracting mwparserfromhell-0.7.dev0-py3.10-linux-x86_64.egg to /usr/local/lib/python3.10/dist-packages
Adding mwparserfromhell 0.7.dev0 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/mwparserfromhell-0.7.dev0-py3.10-linux-x86_64.egg
Processing dependencies for mwparserfromhell==0.7.dev0
Finished processing dependencies for mwparserfromhell==0.7.dev0

Cloning into 'mwparserfromhell'...
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
zip_safe flag not set; analyzing archive contents...
mwparserfromhell.parser.__pycache__._tokenizer.cpython-310: module references __file__

**Comment by LeMoussel** [comment]
It's OK with `pip install mwparserfromhell`
