### ISSUE TITLE
Implicit fallthrough intended?

### ISSUE THREAD

**Issue by r-barnes** [earwig/mwparserfromhell#325]
Is the implicit fallthrough at [this line](https://github.com/earwig/mwparserfromhell/blob/4e73af2fabbbc13915a44f06c283c8bd53558ffa/src/mwparserfromhell/parser/ctokenizer/tok_parse.c#L1561) intentional, or should it be a `break`?

**Comment by earwig** [comment]
It’s intended. This is an error handling case where one of `so` or `sc` failed to allocate so we fall through to clean up the closing tag and propagate the error by returning NULL.On Jul 19, 2024, at 12:20 PM, Richard Barnes ***@***.***> wrote:﻿
Is the implicit fallthrough at this line intentional, or should it be a break?
